#!/system/bin/sh

CAPTURE_FILE=$1;
FINAL_FILE=$2;
CAPTURE_CYCLE_DURATION=$(($3 * 1));

touch $CAPTURE_FILE

TIMESTAMP_BEGIN=$(date +"%s")
logcat -v time > $CAPTURE_FILE&
PID=$!

sleep $CAPTURE_CYCLE_DURATION

KILL=`kill -9 $PID`
TIMESTAMP_END=$(date +"%s")
logcat -c

chmod a+rw $CAPTURE_FILE
cp $CAPTURE_FILE $FINAL_FILE
chmod a+rw $FINAL_FILE
rm $CAPTURE_FILE