package org.rfcx.guardian.utility.rfcx;

import android.content.Context;
import android.database.Cursor;
import android.util.Log;
import org.rfcx.guardian.utility.misc.StringUtils;

public class RfcxGuardianIdentity {

	public RfcxGuardianIdentity(Context context, String appRole) {
		this.logTag = RfcxLog.generateLogTag(appRole, "RfcxGuardianIdentity");
		this.context = context;
		this.appRole = appRole;
		checkSetPreDefinedGuid();
	}

	private String logTag;

	private Context context;
	private String appRole;

	private String guid;
	private String authToken;
	private String keystorePassPhrase;

	private void checkSetPreDefinedGuid() {
		String fromContentProvider = readIdentityInfoFromContentProvider("guid");
		if (fromContentProvider != null) {
			Log.v(logTag, "Predefined Guardian Guid retrieved via content provider");
			setGuid(fromContentProvider);
		} else {
			String fromTxtFile = RfcxPrefs.readFromGuardianRoleTxtFile(this.context, this.logTag, this.appRole, this.appRole, "guid");
			if (fromTxtFile != null) {
				Log.v(logTag, "Predefined Guardian Guid retrieved from file");
				this.guid = fromTxtFile;
			}
		}
	}

	private void checkSetPreDefinedAuthToken() {
		String fromContentProvider = readIdentityInfoFromContentProvider("token");
		if (fromContentProvider != null) {
			Log.v(logTag, "Predefined Auth Token retrieved via content provider");
			setAuthToken(fromContentProvider);
		} else {
			String fromTxtFile = RfcxPrefs.readFromGuardianRoleTxtFile(this.context, this.logTag, this.appRole, this.appRole, "token");
			if (fromTxtFile != null) {
				Log.v(logTag, "Predefined Auth Token retrieved from file");
				this.authToken = fromTxtFile;
			}
		}
	}

	private void checkSetPreDefinedKeystorePassPhrase() {
		String fromContentProvider = readIdentityInfoFromContentProvider("keystore_passphrase");
		if (fromContentProvider != null) {
			Log.v(logTag, "Predefined Keystore Passphrase retrieved via content provider");
			setKeystorePassPhrase(fromContentProvider);
		} else {
			String fromTxtFile = RfcxPrefs.readFromGuardianRoleTxtFile(this.context, this.logTag, this.appRole, this.appRole, "keystore_passphrase");
			if (fromTxtFile != null) {
				Log.v(logTag, "Predefined Keystore Passphrase retrieved from file");
				this.keystorePassPhrase = fromTxtFile;
			}
		}
	}

	public void setGuid(String guid) {
		RfcxPrefs.writeToGuardianRoleTxtFile(this.context, this.logTag, "guid", guid, true);
		this.guid = guid;
	}

	public void setAuthToken(String authToken) {
		RfcxPrefs.writeToGuardianRoleTxtFile(this.context, this.logTag, "token", authToken, true);
		this.authToken = authToken;
	}

	public void setKeystorePassPhrase(String authToken) {
		RfcxPrefs.writeToGuardianRoleTxtFile(this.context, this.logTag, "keystore_passphrase", authToken, true);
		this.authToken = authToken;
	}

	public String getIdentityValue(String idKey) {
		if (idKey.equalsIgnoreCase("guid")) {
			return getGuid();
		} else if (idKey.equalsIgnoreCase("token")) {
			return getAuthToken();
		} else if (idKey.equalsIgnoreCase("keystore_passphrase")) {
			return getKeystorePassphrase();
		} else {
			return null;
		}
	}
	
    public String getGuid() {
		if (this.guid == null) {
			checkSetPreDefinedGuid();
			if (this.guid == null) {
				Log.e(logTag, "Failed to find pre-defined guid.");
		//		setGuid(StringUtils.randomAlphanumericString(12, false));
				setGuid("088567034852");
				Log.e(logTag, "New Guardian Guid generated (random): "+this.guid);
			}
		}
		return this.guid;
    }
    
    public String getAuthToken() {
		if (this.authToken == null) {
			checkSetPreDefinedAuthToken();
			if (this.authToken == null) {
				setAuthToken("18c5378814e7cf0c6bf7db25dd744abb7b91e584");
				Log.e(logTag, "Failed to find pre-defined auth token.");
				Log.e(logTag, "Auth token cannot be generated by the guardian itself. Please re-register this device.");
			}
		}
		return this.authToken;
    }

	public String getKeystorePassphrase() {
		if (this.keystorePassPhrase == null) {
			checkSetPreDefinedKeystorePassPhrase();
			if (this.keystorePassPhrase == null) {
				Log.e(logTag, "Failed to find pre-defined keystore passphrase.");
				Log.e(logTag, "Keystore passphrase cannot be generated by the guardian itself. Please re-register this device.");
			}
		}
		return this.authToken;
	}


	private String readIdentityInfoFromContentProvider(String identityKey) {
		try {

			if (!this.appRole.equalsIgnoreCase("guardian")) {

				Cursor identityCursor = this.context.getContentResolver().query(
						RfcxComm.getUri("guardian", "identity", identityKey),
						RfcxComm.getProjection("guardian", "identity"),
						null, null, null);

				if ((identityCursor != null) && (identityCursor.getCount() > 0)) { if (identityCursor.moveToFirst()) { try { do {
					if (identityCursor.getString(identityCursor.getColumnIndex("identity_key")).equalsIgnoreCase(identityKey)) {
						String identityValue = identityCursor.getString(identityCursor.getColumnIndex("identity_value"));
						return identityValue;
					}
				} while (identityCursor.moveToNext()); } finally { identityCursor.close(); } } }
			}

		} catch (Exception e) {
			RfcxLog.logExc(logTag, e);
		}
		return null;
	}

	public void reSyncGuardianIdentity() {
		if (this.guid != null) { this.guid = null; checkSetPreDefinedGuid(); }
		if (this.authToken != null) { this.authToken = null; checkSetPreDefinedAuthToken(); }
		if (this.keystorePassPhrase != null) { this.keystorePassPhrase = null; checkSetPreDefinedKeystorePassPhrase(); }
	}

	public void reSyncIdentityInExternalRoleViaContentProvider(String targetAppRole, Context context) {
		try {
			Cursor targetAppRoleResponse =
					context.getContentResolver().query(
							RfcxComm.getUri(targetAppRole, "identity_resync", "all"),
							RfcxComm.getProjection(targetAppRole, "identity_resync"),
							null, null, null);
			if (targetAppRoleResponse != null) {
			//	Log.v(logTag, targetAppRoleResponse.toString());
				targetAppRoleResponse.close();
			}
		} catch (Exception e) {
			RfcxLog.logExc(logTag, e);
		}
	}
}
