package org.rfcx.guardian.utility.rfcx;

import android.content.Context;
import android.database.Cursor;
import android.util.Log;
import org.rfcx.guardian.utility.misc.StringUtils;

public class RfcxGuardianIdentity {

	public RfcxGuardianIdentity(Context context, String appRole) {
		this.logTag = RfcxLog.generateLogTag(appRole, "RfcxGuardianIdentity");
		this.context = context;
		this.appRole = appRole;
		checkSetPreDefinedGuid();
	}

	private String logTag;

	private Context context;
	private String appRole;
	private String guid;
	private String authToken;

	private void checkSetPreDefinedGuid() {
		String fromContentProvider = readIdentityInfoFromContentProvider("guid");
		if (fromContentProvider != null) {
			Log.v(logTag, "Predefined Guardian Guid retrieved via content provider");
			this.guid = fromContentProvider;
			RfcxPrefs.writeToGuardianRoleTxtFile(this.context, this.logTag, "guid", this.guid);
		} else {
			String fromTxtFile = RfcxPrefs.readFromGuardianRoleTxtFile(this.context, this.logTag, this.appRole, this.appRole, "guid");
			if (fromTxtFile != null) {
				Log.v(logTag, "Predefined Guardian Guid retrieved from file");
				this.guid = fromTxtFile;
			}
		}
	}

	private void checkSetPreDefinedAuthToken() {
		String fromContentProvider = readIdentityInfoFromContentProvider("token");
		if (fromContentProvider != null) {
			Log.v(logTag, "Predefined Auth Token retrieved via content provider");
			this.authToken = fromContentProvider;
			RfcxPrefs.writeToGuardianRoleTxtFile(this.context, this.logTag, "token", this.authToken);
		} else {
			String fromTxtFile = RfcxPrefs.readFromGuardianRoleTxtFile(this.context, this.logTag, this.appRole, this.appRole, "token");
			if (fromTxtFile != null) {
				Log.v(logTag, "Predefined Auth Token retrieved from file");
				this.authToken = fromTxtFile;
			}
		}
	}

	public void setGuid(String guid) {
		RfcxPrefs.writeToGuardianRoleTxtFile(this.context, this.logTag, "guid", guid);
		this.guid = guid;
	}

	public void setAuthToken(String authToken) {
		RfcxPrefs.writeToGuardianRoleTxtFile(this.context, this.logTag, "token", authToken);
		this.authToken = authToken;
	}
	
    public String getGuid() {
		if (this.guid == null) {
			checkSetPreDefinedGuid();
			if (this.guid == null) {
				Log.e(logTag, "Failed to find pre-defined guid.");
				setGuid(StringUtils.randomAlphanumericString(12, false));
				Log.e(logTag, "New Guardian Guid generated: "+this.guid);
			}
		}
		return this.guid;
    }
    
    public String getAuthToken() {
		if (this.authToken == null) {
			checkSetPreDefinedAuthToken();
			if (this.authToken == null) {
				Log.e(logTag, "Failed to find pre-defined auth token.");
				Log.e(logTag, "Auth token cannot be generated by the guardian itself. Please re-register this device.");
			}
		}
		return this.authToken;
    }


	private String readIdentityInfoFromContentProvider(String identityKey) {
		try {

			if (!this.appRole.equalsIgnoreCase("guardian")) {

				Cursor identityCursor = this.context.getContentResolver().query(
						RfcxComm.getUri("guardian", "identity", identityKey),
						RfcxComm.getProjection("guardian", "identity"),
						null, null, null);

				if ((identityCursor != null) && (identityCursor.getCount() > 0)) { if (identityCursor.moveToFirst()) { try { do {
					if (identityCursor.getString(identityCursor.getColumnIndex("identity_key")).equalsIgnoreCase(identityKey)) {
						String identityValue = identityCursor.getString(identityCursor.getColumnIndex("identity_value"));
//						Log.v(logTag, "Guardian Identity retrieved via Content Provider: '"+identityKey+"' = '"+identityValue+"'");
						return identityValue;
					}
				} while (identityCursor.moveToNext()); } finally { identityCursor.close(); } } }
			}

		} catch (Exception e) {
			RfcxLog.logExc(logTag, e);
		}
		return null;
	}

}
